### ISSUE TITLE
Android Home Assistant Integration with a On/Off Button

### ISSUE THREAD

**Issue by nisgoswami** [hristo-atanasov/Tasmota-IRHVAC#100]
Thanks for the awesome integration , any chance to know how to integrate a On button with the integration , i already modified the card to use a custom switch , but cant figure out how to get it in android (specially samsung notification panel)

Card - <Has a Power Button>
![image](https://user-images.githubusercontent.com/39175883/197305964-bafc3145-4d22-49e7-967e-6f6de62eb512.png)

![image](https://user-images.githubusercontent.com/39175883/197306010-d2216be0-0260-4cde-9363-1b174f1bf552.png)

Is there any way to make a card like this ? 
![image](https://user-images.githubusercontent.com/39175883/197306138-f7d4f64d-0379-4fe2-b0f7-12de6e99bd06.png)

**Comment by hristo-atanasov** [comment]
You can create template switch in Home Assistant and expose it to Samsung, but I don't know how or if it will be displayed where you want it.

**Comment by nao-pon** [comment]
This might be a good idea to ask the HomeAssistant App community.
