### ISSUE TITLE
Adjusting HVAC temperature with remote changes dashboard card temperature to celsius

### ISSUE THREAD

**Issue by HotshotGT** [hristo-atanasov/Tasmota-IRHVAC#107]
Adjusting my device's temperature using this integration with "celsius_mode" set to off properly updates the lovelace card to display the new temperature in Fahrenheit, however, adjusting the temperature via my device's remote causes the card to display temperature in Celsius until I make another adjustment via the card.

I'm fairly certain this is happening because my remote sends commands with "Celsius":"On" even though its screen displays the temperature in Fahrenheit. Would it be possible to account for this behavior in some way? Maybe a setting to convert the temperature in "IrReceived" events back to Fahrenheit if "celsius_mode" is set to off and the event has Celsius set to on?

Here's my IR blaster's console output when making an adjustment via the integration:

> stat/ir_blaster/RESULT = {"IRHVAC":{"Vendor":"DAIKIN152","Model":-1,"Mode":"Auto","Power":"On","Celsius":"Off","Temp":64,"FanSpeed":"Low","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}

Here's the output when my remote is used:

> tele/ir_blaster/RESULT = {"IrReceived":{"Protocol":"DAIKIN152","Bits":152,"Data":"0x11DA27000031250070000000000000C500009D","Repeat":0,"IRHVAC":{"Vendor":"DAIKIN152","Model":-1,"Mode":"Cool","Power":"On","Celsius":"On","Temp":18,"FanSpeed":"Max","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}}

**Comment by hristo-atanasov** [comment]
This behaviour is fully correct. This is how it was ment to do. You set the card the reflect the same data like the remote itself. We are nor recalculating Fahrenheit to Celsius and vice versa. We just display what the remote sends. If remote sends the temperature in Celsius - we display it in Celsius. I'm not sure if I correctly understood what you are trying to achieve. You want the remote to set and display the AC's temperature in celsius, but in the HA card to set and show the temp in Fahrenheit?

**Comment by HotshotGT** [comment]
My remote actually displays temperature in Fahrenheit: https://i.imgur.com/3sqZN4R.jpg

The issue arises when it sends commands to the AC unit, as it sends them in Celsius. This causes the card on my dashboard to switch from 65°F to 18°F when the remote is used. I was just hoping for a way to keep the temperature consistently in Fahrenheit.

**Comment by nao-pon** [comment]
If there is a real remote control with a different unit for temperature display and data to be sent, it seems that we need to convert the unit according to the setting value of “celsius_mode”.

Are there cases where doing this unit conversion will have a negative effect?

**Comment by hristo-atanasov** [comment]
> I also think using the hass config value is a good idea.
> 
> * https://community.home-assistant.io/t/get-the-metric-or-temperature-system-used-in-home-assistant/529024/4?u=nao-pon
> 
> ```python
> if self.hass.config.units.temperature_unit == UnitOfTemperature.CELSIUS:
> ```

This is a good idea. But I think the default value should use it. If later someone wants to change it, there should be a way to do that. What do you think?

**Comment by nao-pon** [comment]
I also think that only the default values are sufficient for applying HA settings.

The problem with unit conversion is that reconverting even in 0.5°C increments will result in inconsistent values. Look at the following spreadsheet.

- https://docs.google.com/spreadsheets/d/e/2PACX-1vQaYIaRL5OaXl4f8gklcjzHCqI6c2gNnS9akta9BZkY8pz2Sp-8EV4S8D-3C98LA08eBSTuLSvfyGRc/pubhtml?gid=0&single=true

We wonder how we should implement this.

**Comment by nao-pon** [comment]
@HotshotGT Daikin air conditioners may support half-degree transmission for correct mapping from Celsius to Fahrenheit. IRremoteESP8266 library may not detect it. There is a related thread in the library issues. By providing the raw data of your real remote, it's possible to add some support, so I'd suggest making a request to the IRremoteESP8266 library.

- https://github.com/crankyoldgit/IRremoteESP8266/issues/1398
- https://github.com/crankyoldgit/IRremoteESP8266/issues/1829

**Comment by nao-pon** [comment]
The automatic HA conversion function has been used.
