### ISSUE TITLE
Services.yaml

### ISSUE THREAD

**Issue by duczz** [hristo-atanasov/Tasmota-IRHVAC#111]
@hristo-atanasov in the services.yaml under "set_swingh"

- left is missing
- left max should be leftmax
- right max should be rightmax

maybe need to edit climate.py too

**Comment by nao-pon** [comment]
@duczz I'll fix about `left is missing`.

There is no problem with `left max` and `right max` because they are normalized by the library.

https://github.com/crankyoldgit/IRremoteESP8266/blob/9d0a9196fd716879897b7bd739fef5dc6ee92551/src/IRac.cpp#L3817-L3836

**Comment by duczz** [comment]
perfect thank you.
hmm strange because, horizontal is not working for me, i will try it tomorrow again and check the logs and ir outputs and post it here
