### ISSUE TITLE
Entity is using self.async_update_ha_state(), without enabling force_update

### ISSUE THREAD

**Issue by bogd** [hristo-atanasov/Tasmota-IRHVAC#112]
When looking through my HomeAssistant logs, I noticed that the message below seems to be logged on every HomeAssistant restart (once for every entity that uses `tasmota_irhvac`):

`Entity climate.bedroom_ac (<class 'custom_components.tasmota_irhvac.climate.TasmotaIrhvac'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.`

As the message says, I am reporting it to the integration author :) . Is this something that we should be concerned about?

**Comment by nao-pon** [comment]
@bogd thanks for letting me know! However, since there is [a similar report](#108) and [PR](#110), I will mark this as a duplicate. We look forward to your continued cooperation. 👍
