### ISSUE TITLE
When air is off after some time it drops the temp to 15

### ISSUE THREAD

**Issue by jbrandek** [hristo-atanasov/Tasmota-IRHVAC#117]
Dont understand why but after some time that the air if off it drops the temperature to 15, and its annoing to set the temp up as it beeps each time.
Is there any way to save the temp when off?

**Comment by hristo-atanasov** [comment]
I think this problem is not coming from the integration, but from the AC and its remote. When you use this custom component it remembers the last received temperature, either from the card in HA, either from the AC remote.

**Comment by jbrandek** [comment]
Is there any way to ignore comands below the minimum temp?

**Comment by hristo-atanasov** [comment]
For the AC or for the component?

**Comment by jbrandek** [comment]
> For the AC or for the component?

For the climate component in HA, that is its an off command do not take the temp or if the temp is below the minimum set temp to dont change ir either

**Comment by jbrandek** [comment]
It is from the remote, the problem

tele/ac_juegos/RESULT = {"IrReceived":{"Protocol":"LG2","Bits":28,"Data":"0x88C0051","DataLSB":"0x1031008A","Repeat":0,"IRHVAC":{"Vendor":"LG2","Model":2,"Mode":"Cool","Power":"Off","Celsius":"On","Temp":15,"FanSpeed":"Auto","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"On","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}}

**Comment by hristo-atanasov** [comment]
This can be implemented. :) I'm thinking of 2 new variables `ignoreOffTemp` and `ignoreOffMode`, that will default to `false`. Some ACs put the mode to `Cool` and the temp to the lowest when turned off. This will help to you and others with similar problems.

**Comment by jbrandek** [comment]
Great, thanks for all the work

**Comment by hristo-atanasov** [comment]
@jbrandek Can you try the code from this branch and give a feedback if it works for you?
https://github.com/hristo-atanasov/Tasmota-IRHVAC/tree/ignore-off-temp
the only thing you have to add to your config is one line
```python
ignore_off_temp: True
```

**Comment by jbrandek** [comment]
> @jbrandek Can you try the code from this branch and give a feedback if it works for you? https://github.com/hristo-atanasov/Tasmota-IRHVAC/tree/ignore-off-temp the only thing you have to add to your config is one line
> 
> ```python
> ignore_off_temp: True
> ```

Sure im not home but as soon as i get there i will try it and let you know 
Thanks

**Comment by jbrandek** [comment]
> @jbrandek Can you try the code from this branch and give a feedback if it works for you? https://github.com/hristo-atanasov/Tasmota-IRHVAC/tree/ignore-off-temp the only thing you have to add to your config is one line
> 
> ```python
> ignore_off_temp: True
> ```

The new functionality is working good, but when i was trying it i saw that it missed i few commands from the remote, it didnt happened before but i will get the normal version back and try it to see if its a problem wirh the receiver or maybe this change something

**Comment by jbrandek** [comment]
keep testing and everything works good, dont know what happend with those lost commands but i tried with console and HA both open and everything works perfect

Thanks

**Comment by hristo-atanasov** [comment]
I'm happy to hear that it works. I'll move to the main branch soon and will make a release so you can stick to the official release. :)
