### ISSUE TITLE
Control additional IR devices via Tasmota-IRHVAC

### ISSUE THREAD

**Issue by ddppddpp** [hristo-atanasov/Tasmota-IRHVAC#121]
I'd like to control additional devices in the line-of-sight of my Tasmota-IRHVAC implementation. I can record the IR packet commands via i.e. broadlink/other IR receiver.
What would be the easiest way to make Tasmota-IRHVAC play them back?

**Comment by jbrandek** [comment]
IRSEND and the same code you received, you can do a script as the example on the documentation

**Comment by hristo-atanasov** [comment]
> I'd like to control additional devices in the line-of-sight of my Tasmota-IRHVAC implementation. I can record the IR packet commands via i.e. broadlink/other IR receiver. What would be the easiest way to make Tasmota-IRHVAC play them back?

Read the full README.md

I've described what topic name you should give to your Tasmota devices in order to use the provided two scripts, that will enable you to controll almost any IR enabled device. I also gave examples for buttons that you can configure to use these scripts.

**Comment by ddppddpp** [comment]
Thanks and sorry for not reading through the readme before posting
