### ISSUE TITLE
Can state_topic be updated from both tele and stat MQTT topics?

### ISSUE THREAD

**Issue by rocwhite168** [hristo-atanasov/Tasmota-IRHVAC#132]
The example configuration suggests `state_topic: "tele/HVAC-1/RESULT"` to update the state "when the tasmota device receives an IR signal (includes own transmission and original remote)". However, I found that the IR receiver is quite directional. It can receive signals from my remote pointing towards the AC but not from the IR emitter soldered side-by-side.

Would it be possible to make it so that the state is updated from both `tele/HVAC-1/RESULT` and `stat/HVAC-1/RESULT`?

**Comment by nao-pon** [comment]
I am rewriting the MQTT subscription process in the HA 2024.6.0 fix in #140, which will enable this request functionality.

**Comment by nao-pon** [comment]
Completed with d030012231600ed6ac4c2c43c644e8c7465c0a3b.

**Comment by nao-pon** [comment]
Starting from Tasmota-IRHVAC 2024.6.1, you can subscribe to both "tele" and "stat" messages. Try the following settings.

```yaml
    state_topic: "tele/your_tasmota_device/RESULT"
    state_topic_2: "stat/your_tasmota_device/RESULT"
```
