### ISSUE TITLE
Mqtt does not update Climate Entity

### ISSUE THREAD

**Issue by fotis3d** [hristo-atanasov/Tasmota-IRHVAC#142]
I do not know if this is an issue but I would like a little help here.

I control my AC via climate entity in HA just fine.

But when I sent with a script or in Tasmota console , an mqtt command with what I want, specific mode, temp, fan control etc it does not update the climate entity.

Which means that I turn on the AC via climate card and turn off via mqtt code the card shows that the AC is still on.

Is this normal ?

**Comment by nao-pon** [comment]
Please checkout https://github.com/hristo-atanasov/Tasmota-IRHVAC/issues/132#issuecomment-2156254797, probably fixes it.
