### ISSUE TITLE
Breaking change in 2024.6.x?  "cannot import name 'MqttAvailability'"

### ISSUE THREAD

**Issue by maddiebeaton** [hristo-atanasov/Tasmota-IRHVAC#143]
I just upgraded from 2024.5.5 to 2024.6.2 and the climate config is no longer loading.  Checking the configuration gets me this error:

```
Platform error 'climate' from integration 'tasmota_irhvac' - cannot import name 'MqttAvailability' from 'homeassistant.components.mqtt.mixins' (/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py)
Platform error 'climate' from integration 'tasmota_irhvac' - cannot import name 'MqttAvailability' from 'homeassistant.components.mqtt.mixins' (/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py)
Platform error 'climate' from integration 'tasmota_irhvac' - cannot import name 'MqttAvailability' from 'homeassistant.components.mqtt.mixins' (/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py)
```

The release notes mention a [backwards-incompatible change with MQTT involving `climate` items](https://www.home-assistant.io/blog/2024/06/05/release-20246/#backward-incompatible-changes), but I'm not sure if it is related.

I can confirm that downgrading back to 2024.5.5 solves the issue.

Thanks!

**Comment by sjaks** [comment]
I faced the same issue and inspired by #141, I downloaded the latest release for version 2024.6.1:

https://github.com/hristo-atanasov/Tasmota-IRHVAC/releases/tag/v2024.6.1

Then reboot and it worked as before!

**Comment by maddiebeaton** [comment]
Ah thanks!  For some reason I expected this to happen in a HACS update or something I suppose.  I'll do that now, apologies for the duplicate issue : )
