### ISSUE TITLE
Will it run on ESP8285?

### ISSUE THREAD

**Issue by iz3man** [hristo-atanasov/Tasmota-IRHVAC#15]
Ordered 2 of these https://www.aliexpress.com/item/1005001288733450.html?spm=a2g0s.9042311.0.0.27424c4dvuXVJY for my DAIKIN A/C control. Before I start tinkering around. Are you aware if these modules will work with your firmware?
For <4€ they seem to be a great little piece of readily made hardware for A/C control.

![Capture](https://user-images.githubusercontent.com/11553674/92400178-c4734d80-f12b-11ea-8be5-ce4e9316e8ce.JPG)

**Comment by hristo-atanasov** [comment]
Not sure. I think it should work fine (Tasmota), but the memory size could be bottleneck.

**Comment by iz3man** [comment]
Maybe I can make a dedicated version where I take out all code not needed by me (only Daikin needed). That should be possible, not? It those modules work they should the IDEAL combination for Tasmota and your custom component.

**Comment by iz3man** [comment]
Just tried it and it flashed fine on the 1MB chip 👍

**Comment by iz3man** [comment]
I can now confirm that EVERYTHING WORKS GREAT. Maybe you'd like this little circuit to your manual. It's a super easy setup and is wired exactly as the nodemcu you use in your setup. So really straight forward.

**Comment by tomlut** [comment]
Do you have a link to the board you used and the Daikin only bin file?

**Comment by iz3man** [comment]
No need for a special Daikin file. It runs genuine tasmota ir file. (Check docs)
Why would you need a Daikin only file?

**Comment by tomlut** [comment]
Because I posted before reading your next message:

> Just tried it and it flashed fine on the 1MB chip

**Comment by iz3man** [comment]
> Because I posted before reading your next message:
> 
> > Just tried it and it flashed fine on the 1MB chip

;) Have fun!
