### ISSUE TITLE
Could this work with zigbee?

### ISSUE THREAD

**Issue by schoren** [hristo-atanasov/Tasmota-IRHVAC#157]
Hi, i've been uising this plugin for some time and it's amazing. I was wondering, since this is based on mqtt, would it work with a generic tuya IR blaster. Is it possible?

Thanks!

**Comment by hristo-atanasov** [comment]
This component works based on Tasmota and IRremoteESP8266 library, so for now it isn't possible to use it with zigbee. MQTT is used as protocol for transporting the commands to Tasmotized ESP8266 or ESP32 and the Tasmota, using IRremoteESP8266 library, sends/receives IR signals to the AC and from the original AC remote.

**Comment by schoren** [comment]
I figured that would be the case, but I needed to make sure. Thanks for your answer and for your awesome work!
