### ISSUE TITLE
Stopped working after update Home Assistant to 2024.11.0

### ISSUE THREAD

**Issue by potat0man** [hristo-atanasov/Tasmota-IRHVAC#161]
getting this error when checking YAML:

`Platform error 'climate' from integration 'tasmota_irhvac' - No module named 'homeassistant.components.mqtt.mixins'`

climate entoty is unavailable

**Comment by aldor443** [comment]
Here it also stopped working 2024.11.0

**Comment by scargill** [comment]
Mine has also stopped working completely since tonights upgrade to 2024.11.0 - Oh dear and it's cold out there... ideas?

**Comment by ewolvy** [comment]
Add me to the list, just after updating. Guess I'll restore a backup of the previous version of home assistant until it can be fixed.

**Comment by scargill** [comment]
> Add me to the list, just after updating. Guess I'll restore a backup of the previous version of home assistant until it can be fixed.

I have to say, the new HA update is not looking good - it's messed up the stat and the proposed new layout options (more sizes) are missing. I guess I'll do the same.

**Comment by ProjektBisarr** [comment]
Same error. Integration not working any more.

**Comment by andredts** [comment]
+1 - Platform error 'climate' from integration 'tasmota_irhvac' - No module named 'homeassistant.components.mqtt.mixins'

**Comment by mateuszdrab** [comment]
It's due to changes in the below, not sure if it's a HASS bug or this integration needs to be updated
https://github.com/home-assistant/core/commit/1773f2aadcff9f4b2e74d4396f8cc666dfc72378#diff-7d9bcd3ad6cf4c6eb1e88e9a6f89fc5de79697ffe22adf3cf4bbdfcf705d32f5L90

**Comment by mojrs10** [comment]
Any info about this problem?
Is abowe fix solution to problem or something is broken on latest HA update?

**Comment by gjetchev** [comment]
PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(MQTT_ENTITY_COMMON_SCHEMA.schema)

This line too and it work again

**Comment by mojrs10** [comment]
That is solved problem.
Tnx

**Comment by scargill** [comment]
This isn't making sense to me - will this integration be updated to work with 24.11.0  or are users supposed to change code in the integration?

**Comment by hristo-atanasov** [comment]
Fix published - v2024.11.7
