### ISSUE TITLE
Doesn't retain hvac_mode, defaults to off after HA restart

### ISSUE THREAD

**Issue by Lauriz7** [hristo-atanasov/Tasmota-IRHVAC#165]
Defaults to off during restart, issue happened after ha update from ha 10.x to ha 11.2 

running latest 2024.11.7 tasmota irhvac

Configuration.yaml:

https://pastebin.com/vwssCMb3

**Comment by lokster** [comment]
Same here - defaults to off after HA restart. Here's my config:

https://pastebin.com/Uyd53iqm

**Comment by hristo-atanasov** [comment]
The problem was't in your config. There was an error by mistake in the code. Should be fixed now.
