### ISSUE TITLE
temp resets to zero when turning off the ac

### ISSUE THREAD

**Issue by biGdada** [hristo-atanasov/Tasmota-IRHVAC#17]
hi.
ive noticed that temperature resets to 0 when i turn off one of my ac's.
i think its because the component sends the off command without temperature and the info it receives from MQTT (/tele/irblaster_name/RESULT) does not include actual temperature, so the component resets it to 0.

have i missed something in the configuration (possibly ignoring the temp when the command is "off") or is it a bug?

i really hope i made myself clear, although when i reread the post i'm not sure i quite understand it myself ;) anyways, if you need examples/logs/further explanations feel free to ask.
thanks.

**Comment by hristo-atanasov** [comment]
Show me Tasmota log (irreceived or IRHVAC), whe you press the 'off'  button on your remote.
