### ISSUE TITLE
default_light_mode

### ISSUE THREAD

**Issue by nagyrobi** [hristo-atanasov/Tasmota-IRHVAC#2]
Please add an option to switch light "off" when the entire unit is "off", and "on", when the unit is in any other mode.

Reason: there's a big red standby LED lighting on the unit when switched off. This is annoying (especially during nights in a bedroom...). It can be turned off with light mode off. But this turns off the entire display too, when the unit is turned on.

If `default_light_mode` is set to off, the standby led and display is also off.
A good trick would be: turn light mode to "off" when device is turned off, and back "on" when the unit is switched to heat, cool, dry etc.

**Comment by hristo-atanasov** [comment]
This can be done with automation that switches the light to On or Off, when the AC is On or Off, using the additional service I made specifically for that case.

**_tasmota_irhvac.set_light_** with payload of:

`{light: "on", entity_id: clima.your_clima_entity_id}`
