### ISSUE TITLE
Problem with AirWell HVAC

### ISSUE THREAD

**Issue by hillaliy** [hristo-atanasov/Tasmota-IRHVAC#20]
Hi thank's for your work.
The code work just fine.
I have AirWell HVAC that a little bit tricky. the first command: "IRHVAC":{"Vendor":"AIRWELL","Model":1,"Power":"On","Mode":"Cool","Celsius":"On","Temp":24,"FanSpeed":"Auto","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}, turn on the AC but if I change the temperature the AC get OFF. it's because the ON and OFF IR command it's the same.
I try to send manual command from Tasmota console with the command: IRhvac {"Vendor":"airwell", "Power":"off","Mode":"cool","FanSpeed":auto,"Temp":22} and it's work O.K.
So to turn the AC on / off the Json need to be with "power":on and when it's on and need  to change temperature or mode cool / heat it's need "power":off
Can you help me with that problem.

**Comment by the-mentor** [comment]
Hi @hillaliy  there is a custom build of tasmota with a fix for this issue that you can try.

you can find it here

https://github.com/ayavilevich/Tasmota/releases/tag/v0.1

hopefully at some point the code will be upstreamed.

-DM

**Comment by ayavilevich** [comment]
@hillaliy see https://github.com/hristo-atanasov/Tasmota-IRHVAC/issues/6#issuecomment-695838907
it is an issue in tasmota. you can try my fork with a fix.

**Comment by hillaliy** [comment]
I try your fix it's work
Thanks.
there is no possible to add dht22 sensor

**Comment by ayavilevich** [comment]
@hillaliy happy to hear it works. you are welcome to close this issue.

your question about the DHT22 is not clear and this is probably not the right place to ask about it.

**Comment by hillaliy** [comment]
How can I see the current temperature on HA.
