### ISSUE TITLE
Persistency on HA restarts

### ISSUE THREAD

**Issue by ayavilevich** [hristo-atanasov/Tasmota-IRHVAC#21]
I would like the climate state to remain after a restart of HA.

What should this component do if I restart?
If it was heating before should it be back to showing heating or should it reset to "off"?
Is the responsibility for persistence with HA in the hands of HA core or each individual component?

**Comment by chicaneau** [comment]
+1 I'd like some persistency too

**Comment by hristo-atanasov** [comment]
Doable if you are not in a hurry! ;)
