### ISSUE TITLE
Set status to unavailable if the tasmota IR blaster/receiver goes out of network

### ISSUE THREAD

**Issue by RobinSinghNanda** [hristo-atanasov/Tasmota-IRHVAC#22]
I am currently facing a issue where sometimes my tasmota IR blaster/receiver discounts randomly disconnects from the network (poor wifi connection). Currently there is no indication on home assistant on where the IR HVAC can take commands or not. The status of device still show as available. Please add a feature to change the status to unavailable in case the it blaster/receiver device goes out of the network.

It can be achieved using the availability_topic feature of tasmota.
availability_topic: "tele/<device_topic>/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

I can also work on this feature in case no one is available.

**Comment by hristo-atanasov** [comment]
Implemented in v2021.12.18
