### ISSUE TITLE
If vendor not on lowercase, state update not working

### ISSUE THREAD

**Issue by avishayil** [hristo-atanasov/Tasmota-IRHVAC#24]
I'll fix this in a PR

**Comment by hristo-atanasov** [comment]
Your PR fixes a problem, that is in common with only one protocol/vendor, but if some of the vendors work only in upper case this will be a problem. If we accept the you PR and if someone needs to use the vendor in uppercase it would not be possible. If we leave it like this everyone can use it as needed.

**Comment by avishayil** [comment]
Hi @hristo-atanasov in my house I have 2 air conditioners, both vendors were uppercase.

My code only lowercases the vendor name on the Python script that controls HA state, how would that affect the vendors that are working only with uppercase?

**Comment by hristo-atanasov** [comment]
@avishayil Sorry, you were right! I was wondering how lots of people are vahing this issue, but the code actually works in my case. It seems I have used a custom version version of my custom component. I merged, but now I think your PR may lead to some sending IR issues - usualy Tasmota expects Vendor/Protocol in uppercase. Actually this lowercase check is a bug, made by me by mistake -  just one more paste.

**Comment by hristo-atanasov** [comment]
Ok.. The code is changed! now the vendor should be exactly like everyone see it in Tasmota console. With the same casing. So remember, if you update to fix your vendor casing. This way if Tasmota or IRremoteESP8266 change their requirements I don't have to rewrite the code. And once more - tank you for pointing me the bug. :)
