### ISSUE TITLE
Climate card does not update with the state_topic

### ISSUE THREAD

**Issue by dedalusjinja** [hristo-atanasov/Tasmota-IRHVAC#26]
The card is not updated if I control the air conditioner with the remote control, but I can correctly control it from HA. I have tried both Daikin and Gree but it doesn't change, I get the message correctly if I listen to MQTT. Some idea? Thanks

**Comment by hristo-atanasov** [comment]
Do you use some of the releases or the master branch?

**Comment by dedalusjinja** [comment]
The master branch

**Comment by hristo-atanasov** [comment]
can you see any error or warnings in HA log that has in common with tasmota_irhvac?

**Comment by dedalusjinja** [comment]
no kind of error in the log.  I tried with several receivers, I got the files and configurations of a friend who has it working but I do not modify the card

**Comment by hristo-atanasov** [comment]
Hmm .. Interesting .. Can you write the "vendor:" or "protocol:" in lowercase (with small letters) in your config, restart HA and try again?

**Comment by dedalusjinja** [comment]
It does not change. Maybe this can help, I have created a mqtt sensor

sensor:
   - platform: mqtt
     state_topic: "tele / test / RESULT"

and not even this sensor acquires the remote control code of the air conditioner, but that of the TV does. While if I listen to Mqtt I see both codes

**Comment by dedalusjinja** [comment]
this error came to me when checking config for version 118:
Testing configuration at /tmp/config
WARNING:homeassistant.components.climate:ClimateDevice is deprecated, modify TasmotaIrhvac to extend ClimateEntity

**Comment by tigers75** [comment]
Hi, I write here because I had the same issue with a Daikin air conditioner (model "-1" in the TasmotaIRHVAC controller).
It did send commands thru the blaster but did not update the state in HA when sending commands with the remote.
I fixed it following your advice and renaming the protocol as "daikin" - lowercase BUT both the TASMOTA IrReceived JSON and the MQTT "RESULT" topic show "DAIKIN" - all uppercase.
**I think this should be highlighted in the docs., because it's not easy to track down.** I was lucky and find this issue as "open" but once it'll be closed I think I'd be diffilut to track down.
Thanks for the great addon.

**Comment by hristo-atanasov** [comment]
I'm no shure what the problem could be. If anyone can share any oppinion here, it would be great. Looks like some issue with MQTT, or the MQTT broker .. Not sure.

**Comment by tigers75** [comment]
The only thing I noticed is that also the operating modes have to be written all lowercase in configuration.yaml, while in Tasmota they appear with the first letter capitalized (in tasmota I see "Heat", but in config I must write "heat"). Since all home assistant names must be lowercase I think maybe that's related to it? 
Anyway if it works it's not a big problem, but I'd point it out in the examples.

**Comment by tigers75** [comment]
That's not my problem anyway: as soon as I put the vendor as lowercase everything works (maybe my message is just shorter than the limit).

**Comment by hristo-atanasov** [comment]
@tigers75  I got it from the first message. No need to constantly comment about it. Read this:
#https://github.com/hristo-atanasov/Tasmota-IRHVAC/issues/28
Master branch is updated already.
And put the vendor exactly as you see it in Tasmota console.

**Comment by dedalusjinja** [comment]
after a long time that I did not test I find two errors in the log:


`Logger: homeassistant.util.logging
Source: util/logging.py:108 
First occurred: 13:36:34 (1 occurrences) 
Last logged: 13:36:34
Exception in message_received when handling msg on 'tele/sala/RESULT': '{"IrReceived":{"Protocol":"GREE","Bits":64,"Data":"0x1A03605000200090","Repeat":0,"IRHVAC":{"Vendor":"GREE","Model":1,"Power":"on","Mode":"dry","Celsius":"on","Temp":19,"FanSpeed":"min","SwingV":"auto","SwingH":"off","Quiet":"off","Turbo":"off","Econo":"off","Light":"on","Filter":"off","Clean":"off","Beep":"off","Sleep":-1}}}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 35, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 187, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1179, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 865, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.sens_prova. State max length is 255 characters.`


`Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:468 
Integration: MQTT (documentation, issues) 
First occurred: 13:36:34 (1 occurrences) 
Last logged: 13:36:34
Invalid modes mode: {"IrReceived":{"Protocol":"GREE","Bits":64,"Data":"0x1A03605000200090","Repeat":0,"IRHVAC":{"Vendor":"GREE","Model":1,"Power":"on","Mode":"dry","Celsius":"on","Temp":19,"FanSpeed":"min","SwingV":"auto","SwingH":"off","Quiet":"off","Turbo":"off","Econo":"off","Light":"on","Filter":"off","Clean":"off","Beep":"off","Sleep":-1}}}`


advice about it?
