### ISSUE TITLE
add .lower() in vendor check

### ISSUE THREAD

**Issue by yoav1000** [hristo-atanasov/Tasmota-IRHVAC#28]
https://github.com/hristo-atanasov/Tasmota-IRHVAC/blob/ed3d533e70d4a21484a0a87279b3752010f4d749/custom_components/tasmota_irhvac/climate.py#L551

should be self._vendor.lower() as all examples show protocol should be caps

**Comment by hristo-atanasov** [comment]
This bug is fixed in the Master branch of the repository. If you get the code from the there, you should use the "vendor" exactly as it is shown in Tasmota console (with the same casing).
