### ISSUE TITLE
Error in Home Assistant 2021.6 No 'version' key

### ISSUE THREAD

**Issue by denisapokin** [hristo-atanasov/Tasmota-IRHVAC#38]
Logger: homeassistant.loader
Source: loader.py:794 
First occurred: 13:35:47 (1 occurrences) 
Last logged:   ##13:35:47

No 'version' key in the manifest file for custom integration 'tasmota_irhvac'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'tasmota_irhvac'

**Comment by voltagex** [comment]
Weirdly, I'm still getting this in my logs even when running the component from git master.

**Comment by hristo-atanasov** [comment]
Do you still have the issue?

**Comment by GhettoDubs** [comment]
I get error:
"Platform error climate.tasmota_irhvac - Integration 'tasmota_irhvac' not found."
With latest version core-2021.6.0, supervisor-2021.05.4

**Comment by denisapokin** [comment]
> Do you still have the issue?

After updating the custom component, the error disappeared. If I understand correctly in the file " manifest.json" the required version key was added. Thanks!
