### ISSUE TITLE
swing mode pasasonic

### ISSUE THREAD

**Issue by riddik14** [hristo-atanasov/Tasmota-IRHVAC#45]
can you add swing mode vertical for panasonic

my panasonic airconditional have this mode for swing
Highest
High
Middle
Low
Lowest
Auto

the code for tasmota is

{"Vendor": "PANASONIC_AC", "Model": "-1", "Power": "on", "Mode": "dry", "Celsius": "on", "Temp": 23, "FanSpeed": "auto", "SwingV": "off", "SwingH": "off", "Quiet": "off", "Turbo": "off", "Econo": "off", "Light": "off", "Filter": "off", "Clean": "off", "Beep": "off", "Sleep": -1}

thank you

**Comment by cociweb** [comment]
Hello @nao-pon,
Unfortunatelly, the [PR](https://github.com/hristo-atanasov/Tasmota-IRHVAC/pull/52) does not resolve the original problem.
the swing has only 4 options: off, vertical, horizontal, or both. For example in the mqtt it looks like this:
`...."SwingV":"Auto","SwingH":"Off",...`
I think @riddik14 suggested that it should be a choosable list for swingV as the element of the following possible values from a list:

- Auto, Automatic, On, Swing
- Off, Stop
- Min, Minimum, Lowest, Bottom, Down
- Low
- Mid, Middle, Med, Medium, Centre, Center
- High, Hi
- Highest, Max, Maximum, Top, Up

I think this is the same situation for the horizontal, where the values also can be very various:

- Auto, Automatic, On, Swing
- Off, Stop
- LeftMax, Left Max, MaxLeft, Max Left, FarLeft, Far Left
- Left
- Mid, Middle, Med, Medium, Centre, Center
- Right
- RightMax, Right Max, MaxRight, Max Right, FarRight, Far Right
- Wide

So the ultimate solution would be 2 dropdownlist where the above mentioned predefinied options would be choosable (eg. the fan mode) So the outbut would be something like `...."SwingV":"Medium","SwingH":"RightMax",...`.

Some example from: [Swing section](https://tasmota.github.io/docs/Tasmota-IR/#sending-irhvac-commands) from Tasmota.
The count of the lists on bit levels are the maximum of 8-8 possible states (limit of the IrRemoteESP8266 library).

I'll bet that the original/inbuilt climate schema supports the current working method, so the values are chooseable from the "off, vertical, horizontal, or both" options for swing:
![image](https://user-images.githubusercontent.com/1935413/147977156-50513b62-cb90-4cb5-922e-37bfa1a7b7e1.png)

**Comment by hristo-atanasov** [comment]
@cociweb Well, when HA changes its climate integration to support it, we will change our integrationt to support it too. For now, we have only one dropdown. I hope HA will add second one soon.

**Comment by nao-pon** [comment]
One option is to give up wind direction control in HA UI and control it with an IR remote controller.
In this integration, the control value of the IR remote controller is saved, so once set, the wind direction will not change due to temperature changes by HA.

The following settings are available:
`supported_swing_list: []`

**Comment by nao-pon** [comment]
Added set_swingv, set_swingh services in v2022.08.30. Also reverted the vane position on swing-off to its previous fixed position.

We can now control the vane's swing and position. 👍 

A blueprint for an automation that uses dropdown inputs and services can be found below.

- https://gist.github.com/nao-pon/0db4765bc35727e7c84434d405f9c0a6


![FireShot Capture 044 - 管理者パネル – Home Assistant - hypha duckdns org](https://user-images.githubusercontent.com/1412630/187568158-e556090c-bc3a-457b-a133-c45ff7e0cada.png)
![FireShot Capture 047 - 管理者パネル – Home Assistant - hypha duckdns org (1)](https://user-images.githubusercontent.com/1412630/187568166-58e26363-d25a-44e4-ac1e-fd3041f76e19.png)

**Comment by bilogic** [comment]
@nao-pon what is the JSON to send in tasmota's console to control the swing?

**Comment by bilogic** [comment]
oh got it, `"SwingV":"lowest"`
