### ISSUE TITLE
Issue with 2 beeps and not powering off in lovelance

### ISSUE THREAD

**Issue by PedroGdiaz** [hristo-atanasov/Tasmota-IRHVAC#46]
Hi Hristo,
I am very happy with the integration you have build, it is awesome!!!
Currently, I am having two issues using SAMSUNG_AC:

1. I have an IR received and all reflect in Lovelace except for off. If I off with remote it does not reflect in lovelance
2. When I send a command from Lovelace the AC always beeps 2 times even do only 1 MQTT is sent. I have one that has a digital display and I notice that the first beep sets it to 24 and the second beep to the desired temperature

My configuration
![image](https://user-images.githubusercontent.com/10461168/134841512-07101933-ff0c-4f2c-bba0-e4abfa327531.png)

And this is the Tasmota console logs
![image](https://user-images.githubusercontent.com/10461168/134841528-120815c4-3c65-4c4f-8330-4f8ce525989a.png)

This is the command that beeps 2 times
IRHVAC {"Vendor": "SAMSUNG_AC", "Model": "-1", "Power": "on", "Mode": "cool", "Celsius": "On", "Temp": 26.0, "FanSpeed": "min", "SwingV": "off", "SwingH": "off", "Quiet": "off", "Turbo": "off", "Econo": "off", "Light": "on", "Filter": "off", "Clean": "off", "Beep": "off", "Sleep": "-1"}

I really hope that I can get some help on this 🥇

**Comment by hristo-atanasov** [comment]
Can you show me the log from Tasmota console after you have used the original IR remote for your AC?
One when the AC is already turned ON and you just change the temperature and one when the AC is already ON and you try to turn it OFF.

**Comment by PedroGdiaz** [comment]
Hi Hristo, thanks for getting back,
 manage to solve the problem of OFF reflecting on Lavelance by doing this change to your code in version 2021.7.15:
![image](https://user-images.githubusercontent.com/10461168/136643918-92ec0f02-2098-4cac-8f3a-9ec6c0a981d7.png)

The logs you requesting:
- One when the AC is already turned ON and you just change the temperature
![image](https://user-images.githubusercontent.com/10461168/136643927-043700ed-49ba-47aa-87b7-6440060e13e6.png)
- One when the AC is already ON and you try to turn it OFF
![image](https://user-images.githubusercontent.com/10461168/136643942-ff021ca2-c308-4d24-b251-0899d368bfd1.png)

The two beeps problem still happening.

**Comment by Lauriz7** [comment]
> As sometimes the AC can receive invalid payload and can "try to settle" with the situation, they can change some options that are received. I see you have set `light: "on"`. Is it supported? If it is unsupported you can try to set it as off by default and check if double beep stops. Edit: I see you have it received by the remote, but try it as I'm not sure how the ESP IRREMOTE 8266 library internally work for each AC brand and model. Could solve the problem.

I have the same problem with two beeps. Quite an big problem actually. So I have tried your suggestions with lights on, but it did not help. The light function works properly if turned on as well. so thats not the problem. Any other ideas?
