### ISSUE TITLE
Weird Daikin AC

### ISSUE THREAD

**Issue by angsanley** [hristo-atanasov/Tasmota-IRHVAC#47]
Hello,

I have a Daikin AC that is working fine with Tasmota and IrHvac except that there's a weird quirk with this kind of Daikin AC. I'm using DAIKIN64.

So this AC doesn't have a separate on and off command. Instead, the AC handles the toggle itself, the remote only sends "On" command to toggle the power state.

If we send
`{"IRHVAC":{"Vendor":"DAIKIN64","Model":-1,"Power":"Off"}` 
while the AC is on or off, it will beep and do nothing. 

But, if we send 
`{"IRHVAC":{"Vendor":"DAIKIN64","Model":-1,"Power":"On"}` 
while the AC is off, it will turn on.

And also vice versa, if we send 
`{"IRHVAC":{"Vendor":"DAIKIN64","Model":-1,"Power":"On"}` 
while the AC is on, it will turn off.

So, is there's any possibility to change the toggling behavior to only send the `Power` command if we want to change the power state?

I think the `Power` command here is not to set the power state, but to toggle it.

Thank you!

**Comment by angsanley** [comment]
Fixed with #52.

**Comment by orthobots** [comment]
Hi @angsanley , sorry to bump an old topic. 
I recently integrated this into my 1 year old daikin unit that weirdly runs off the ancient DAIKIN64 protocol as well. 

I'm facing an issue where the integration and the remote goes out of sync often, ie, after turning off mains, and later turning back on with the remote, the state becomes inverted. ie, when turned on via HASS, it turns off, when turned off via HASS, it turns on. 

Thanks!

**Comment by angsanley** [comment]
> Hi @angsanley , sorry to bump an old topic. I recently integrated this into my 1 year old daikin unit that weirdly runs off the ancient DAIKIN64 protocol as well.
> 
> I'm facing an issue where the integration and the remote goes out of sync often, ie, after turning off mains, and later turning back on with the remote, the state becomes inverted. ie, when turned on via HASS, it turns off, when turned off via HASS, it turns on.
> 
> Thanks!

Hey, sorry for late reply. I haven't played with Home Assistant for a while now so I don't know any new updates regarding this anymore. But the last time I tried this it was already fixed with #52 maybe that helps.

**Comment by orthobots** [comment]
> > Hi @angsanley , sorry to bump an old topic. I recently integrated this into my 1 year old daikin unit that weirdly runs off the ancient DAIKIN64 protocol as well.
> > I'm facing an issue where the integration and the remote goes out of sync often, ie, after turning off mains, and later turning back on with the remote, the state becomes inverted. ie, when turned on via HASS, it turns off, when turned off via HASS, it turns on.
> > Thanks!
> 
> Hey, sorry for late reply. I haven't played with Home Assistant for a while now so I don't know any new updates regarding this anymore. But the last time I tried this it was already fixed with #52 maybe that helps.

Hi, Thanks for replying!

I've checked out #52, don't see any mention of this being resolved sadly :(
