### ISSUE TITLE
Not working in HA 12.0 update

### ISSUE THREAD

**Issue by Lauriz7** [hristo-atanasov/Tasmota-IRHVAC#50]
Not working anymore, mqtt issues seen in log.

https://pastebin.com/56gh0zWW (log)
https://pastebin.com/dxdLBBrw (yaml)

Running Tasmota-ir 10.0

**Comment by tjhorner** [comment]
Can confirm. Please fix this issue ASAP, I am very cold.

**Comment by tjhorner** [comment]
It looks like this change was caused by [`mqtt.async_publish` turning into a coroutine](https://github.com/home-assistant/core/pull/58441). It needs to be awaited or otherwise dealt with as a coroutine rather than a normal function call.

**Comment by stibbzy** [comment]
Also confirming I have the same issue since upgrading to 2021.12...

**Comment by stibbzy** [comment]
I have (at least as far as I can tell) fixed the issue by changing line 1006 of climate.py to self.hass.async_create_task(mqtt.async_publish(self.hass, self.topic, payload))

**Comment by nao-pon** [comment]
I solved it by making the following changes in my repository.

https://github.com/nao-pon/Tasmota-IRHVAC/commit/f968c9200d087f7237935d2bedf362fb5978a7f6

**Comment by akdri** [comment]
also work's changing the last line of climate.py 
 mqtt.async_publish(self.hass, self.topic, payload) -->  mqtt.publish(self.hass, self.topic, payload)

**Comment by hristo-atanasov** [comment]
Ok, I see there is a problem .. I'll read the change log .. And I have to update to the newest HA version too .. :)

**Comment by chicaneau** [comment]
> also work's changing the last line of climate.py mqtt.async_publish(self.hass, self.topic, payload) --> mqtt.publish(self.hass, self.topic, payload)

can confirm this works for me too, thanks for the fix. This appears to be the cleanest way to fix the problem

**Comment by Lauriz7** [comment]
> Ok, I see there is a problem .. I'll read the change log .. And I have to update to the newest HA version too .. :)

Can I also ask you to include fix AC power off in the new version? I think it was relevant for Panasonic/Daikin AC's

**Comment by kzagatti** [comment]
> also work's changing the last line of climate.py mqtt.async_publish(self.hass, self.topic, payload) --> mqtt.publish(self.hass, self.topic, payload)

Confirmed this works here too! Thanks

**Comment by hristo-atanasov** [comment]
> I solved it by making the following changes in my repository.
> 
> [nao-pon@f968c92](https://github.com/nao-pon/Tasmota-IRHVAC/commit/f968c9200d087f7237935d2bedf362fb5978a7f6)

The new version fixes the problem. Thanks to @nao-pon! I want to apologize to everyone experiencing problems because of my slow fixes.

**Comment by nao-pon** [comment]
I will soon create a PR that may solve some of the issues reported in Issues of this repository.
I would like to ask everyone to test.
