### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ahmaddxb** [hristo-atanasov/Tasmota-IRHVAC#55]
Tasmota IR 10.0.0
Home Assistant 2021.12.3

![image](https://user-images.githubusercontent.com/43728586/146925631-87a0a78f-ebe7-4ce3-822f-11de7a32dcda.png)

stopped working for me. Buttons dont work temp cant be set, i see no output over mqtt

**Comment by nao-pon** [comment]
@ahmaddxb The LWT MQTT message may not be processed correctly.

Please let us know the value of `command_topic`. The device name may be masked.

**Comment by nao-pon** [comment]
I created PR #56. Try setting the `availability_topic` option correctly using the following file:

https://github.com/hristo-atanasov/Tasmota-IRHVAC/blob/cef518a4a01472b9f7a9caff68998d27add68afc/custom_components/tasmota_irhvac/climate.py

If you are customizing the full Tasmota topic, you need to set the
option `availability_topic` correctly.

`availability_topic: "[TOPIC]/tele/LWT"`

The default is `availability_topic: "tele/[TOPIC]/LWT"`.

**Comment by ahmaddxb** [comment]
command_topic: "cmnd/sonoff/irbridge/irhvac"

**Comment by ahmaddxb** [comment]
did the changes all good now
