### ISSUE TITLE
Missing operational data after restart and no temperature sensor

### ISSUE THREAD

**Issue by Lauriz7** [hristo-atanasov/Tasmota-IRHVAC#57]
Hello,

After upgrading to the latest tasmotairhvac, and latest HA 12.4, i noticed that:
1) temperature sensor does not work, shows N/A 
2) after restart 1 out of 2 climate entities does not report previous state (mode and temperature), however if automation triggered or manually adjusted it works, but does not go back to previous state.

I cannot figure out if 1) and 2) are related to each other. But temperature sensor never works and does not come back like operational data in 2).

I have HA log here with this error https://pastebin.com/dpKgEA9j
my yaml https://pastebin.com/dwiG15U5 (samsung one is the problem)

Screenshot of issue (lovelace)
https://i.postimg.cc/7L6v8Wmf/Capture.jpg

UPDATE: Updated to HA 12.5 and temperature sensor is fixed! issue 2) is not fixed still

**Comment by nao-pon** [comment]
@Lauriz7 #60 may be relevant. Hopefully the #61 PR may help.

**Comment by hristo-atanasov** [comment]
@Lauriz7 try updating Tasmota IRHVAC to the latest release (v2022.01.04) and see if the issue is fixed.

**Comment by Lauriz7** [comment]
Issue is fixed, works with HA 12.9
