### ISSUE TITLE
HACS Integration

### ISSUE THREAD

**Issue by somejavadev** [hristo-atanasov/Tasmota-IRHVAC#58]
Hi, thanks for this project, is there a possibility to get this component integrated with HACS for easier updating and integration into Home assistant?

**Comment by cociweb** [comment]
Hello,
It's already available from HACS:
1) You need to add as a custom [repository](https://github.com/hristo-atanasov/Tasmota-IRHVAC/) in the 3 dotted menu as in this [guide](https://hacs.xyz/docs/faq/custom_repositories)) 
2) Install the addon
3) Restart HA
4) Add your customized configuration to the [configuration.yaml](https://github.com/hristo-atanasov/Tasmota-IRHVAC/blob/master/examples/configuration.yaml)
5) Restart HA again to take consideration your config

Everytime, when a new release (or pre-release) is created for this repository, it will notify you via HACS.

**Comment by leranp** [comment]
After adding to HACS and deleting the old version i now have an error message

Platform error: climate - Integration 'tasmota_irhvac' not found
