### ISSUE TITLE
HACS compatibility

### ISSUE THREAD

**Issue by vitorma** [hristo-atanasov/Tasmota-IRHVAC#7]
Would be nice to have HACS compatibility with this repo.

![Captura de tela de 2020-07-29 10-30-32](https://user-images.githubusercontent.com/624208/88806383-b7575c00-d186-11ea-91fd-187189af33ab.png)

**Comment by hoangtuit** [comment]
Hi,

I still can't add to HACS (v.1.5.2)

![image](https://user-images.githubusercontent.com/12227977/91651403-81bfce80-eab6-11ea-93c5-0202ccaa540a.png)

**Comment by diogos88** [comment]
Missing file info.md to be able to add into HACS.

**Comment by chicaneau** [comment]
I am unable to add via HACS either

**Comment by hristo-atanasov** [comment]
We're not HACS compatible yet. :)

**Comment by jcisio** [comment]
New PR https://github.com/hristo-atanasov/Tasmota-IRHVAC/pull/27/files

It's strange, because even without `hacs.json`, when I clone the repository and add my repository without any change, it works. However, per document, that file is required, so it should be added. The minimum requirement version 0.94 is from the README.

**Comment by kiwipaulrob** [comment]
Thanks for all your work on this great HA add in (and Merry Christmas!)

I see that you added hacs.json but HACS  won't allow me to add your github repository if I use the root url and if use

https://github.com/hristo-atanasov/Tasmota-IRHVAC/

It says - Repostitory structure for v0.110.0 is not compliant

Any thoughts?

**Comment by chicaneau** [comment]
from doing a little digging, i believe it's not working with HACS due to not having any topics. according to [https://hacs.xyz/docs/publish/start](url) you need to have topics, readme (or info.md) and hacs.json with at least a 'name' declared.
This repo appears to have all these things except for topics. I could be wrong, but something to try and doesnt require a push

**Comment by hristo-atanasov** [comment]
What should be the content of this topics file?

**Comment by chicaneau** [comment]
I don’t think it’s a file. It’s more like tags. See here

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics

**Comment by jcisio** [comment]
That was what I had expected too, but I tested and it was not that. E.g. my forked repo (for the previous PR) does not have any topic, and still work https://github.com/jcisio/Tasmota-IRHVAC. My forked repo, completely identical, is compatible but this repo is not. I don't know why :(

**Comment by jcisio** [comment]
On a second thought, maybe it is because the forked repos are more recent? But you are right, it worth trying to add a topic.

**Comment by hristo-atanasov** [comment]
Okay, guys, try adding custom repository "https://github.com/hristo-atanasov/Tasmota-IRHVAC/ "to HACS. It should now work. :)

**Comment by hristo-atanasov** [comment]
I'm not sure what I have to do, to add a logo, so if someone knows - pleace, enlight me! :)

**Comment by jcisio** [comment]
It looks like that all integration logos are brands, and they are centralized at https://github.com/home-assistant/brands. No fancy custom logo, so maybe it does not matter here.

**Comment by hristo-atanasov** [comment]
Yes, they are, but the logo is already there (Tasmota logo), but I don't know how to reuse it. I have a permission by Tasmota's screator to use it. But I don't know how to reuse it, without resubmiting it again.

**Comment by chicaneau** [comment]
Not too sure about the logo. But i can confirm that this component now adds and updates successfully from HACS.

Thankyou so much for doing that :)

**Comment by hristo-atanasov** [comment]
We are practical guys, so who (except me) cares about the logo .. ;)

**Comment by hristo-atanasov** [comment]
Well .. Time to close this issue! Happy HACS-ing ;)
