### ISSUE TITLE
ValueError: 'unavailable' is not a valid HVACMode

### ISSUE THREAD

**Issue by hristo-atanasov** [hristo-atanasov/Tasmota-IRHVAC#71]
The error is a new "feature" in Home Assistan from v. 2022.05+

**Comment by dmamontov** [comment]
@hristo-atanasov Try my PR https://github.com/hristo-atanasov/Tasmota-IRHVAC/pull/72

**Comment by ahmetem** [comment]
Logger: homeassistant.util.logging
Source: util/logging.py:114
First occurred: 12:43:51 (1 occurrences)
Last logged: 12:43:51

Exception in availability_message_received when handling msg on 'tele/klima_2935BE/LWT': 'Online' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 448, in availability_message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state return HVACMode(self.hvac_mode).value File "/usr/local/lib/python3.9/enum.py", line 384, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.9/enum.py", line 702, in __new__ raise ve_exc ValueError: 'unknown' is not a valid HVACMode

**Comment by chicaneau** [comment]
Thanks for the PR @dmamontov I have updated my climate.py and the entities are at least creating now. However I am unable to set a temperature on 2 of my climate entities. I'm not exactly sure what the difference is between mine. However 1 works fine and 2 dont. The 1 that does work wasnt affected by the unavailable bug either though.

![image](https://user-images.githubusercontent.com/26127713/169201966-eea80a89-b473-4c83-bc98-9b7718f1a48a.png)

**Comment by nao-pon** [comment]
I fixed an issue with a value of ‘unknown’ in #73, but I don't understand why the value is ‘unavailable’.
