### ISSUE TITLE
Platform error climate.tasmota_irhvac - Exception importing custom_components.tasmota_irhvac.climate

### ISSUE THREAD

**Issue by xinux87** [hristo-atanasov/Tasmota-IRHVAC#77]
Hi everyone, i'm getting this error after the last update of HA, in the check configuration:

Platform error climate.tasmota_irhvac - Exception importing custom_components.tasmota_irhvac.climate

Home Assistant Core 2022.6.1
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

Anyone is having the same issues?

**Comment by abra5umente** [comment]
I'm also getting this. Have tried reinstalling and it's made no difference - I'm guessing that HA has updated some code base which makes this not work anymore.

**Comment by abra5umente** [comment]
Looks like there was a commit pushed to fix this, #75

I'm just testing it out now, will report back if it resolved.

**Comment by abra5umente** [comment]
Can confirm that #75 has resolved the issue - just copy and paste the changed code into the custom_components/tasmota_irhvac/climate.py file, remove your climate config yaml from the configuration.yaml file, reload HASS, put your yaml back, restart again, and it's all working.

**Comment by kaciker** [comment]
Confirmed, it's working after such modification
Thansk a lot

**Comment by hristo-atanasov** [comment]
Fixed in #75 and release v2022.06.04
