### ISSUE TITLE
Presets support is disabled when the swing mode list is not empty

### ISSUE THREAD

**Issue by 3cky** [hristo-atanasov/Tasmota-IRHVAC#81]
Since `_support_flags` field currently is not updated but rewritten when the [SUPPORT_SWING_MODE flag is set](https://github.com/hristo-atanasov/Tasmota-IRHVAC/blob/6e9c51b62a776e54909d66f4b154337ba42eedb1/custom_components/tasmota_irhvac/climate.py#L443), the SUPPORT_PRESET_MODE flag will be effectively disabled if swing mode list is not empty. I think it's a bug.

**Comment by nao-pon** [comment]
@3cky This certainly seems like a bug. Created a PR on #82. Thanks! 👍
