### ISSUE TITLE
state not saved

### ISSUE THREAD

**Issue by biGdada** [hristo-atanasov/Tasmota-IRHVAC#83]
i've updated hass to 2022.8.3, and since the update the state of the AC is not being kept on restart. it seems like the state is not saved (i checked the entry in core.restore_state).

**Comment by biGdada** [comment]
have you tried to restart home assistant while one of the ACs is running? 
mine revert to being off.

**Comment by nao-pon** [comment]
Yes, the working one will be restored in the proper mode.

Is the content of core.restore_state stored with a different value than it actually is?

**Comment by biGdada** [comment]
it is not changed at all. the state is stuck on "off" no matter what i do

**Comment by nao-pon** [comment]
I'm concerned that the file core.restore_state is corrupted. Is the state of other entities updated?

**Comment by biGdada** [comment]
i tried to move core.restore_state and restart HA. the file was recreated but the problem persists. thus i dont think it's corrupted.
but, i just tried another entry and its also not updated. might be something wrong with my installation. i think you can close the bug report now, sorry for all the noise.

**Comment by nao-pon** [comment]
Yes. I will close this, but please reopen if you find problems with this integration.
